### ISSUE TITLE
Update documentation regarding the CronJob

### ISSUE THREAD

**Issue by Gregory-Pereira** [thoth-station/graph-sync-job#648]
As a part of improving the migration of the Thoth graph database between staging and prod, I have been following [this PR](https://github.com/thoth-station/storages/pull/2625/files) which randomizes adviser document IDs, allowing for multiple jobs to be run in parallel. After this PR has been completed, the version for the `thoth.storages` should be bumped in `thoth-station/sync-job` repo (not this one). However after that, it will need to be converted into a Cronjob, which can run in Openshift. I was reading through the documentation in this repository to figure out how to do that, and if the resource for the `graph-sync-job` was available or constructed here. Instead, I found documentation telling me to look for the `openshift/` solver in the root of this repository for the Cronjob, however it appears that this has been deprecated. We should clarify this in the documentation and potentially point to our procedure for constructing new CronJobs.

/cc @harshad16

**Comment by fridex** [comment]
All the deployment manifests live in the [thoth-station/thoth-application](https://github.com/thoth-station/thoth-application/) repository. I think we forgot to reflect this fact in docs.

**Comment by goern** [comment]
ping
